### ISSUE TITLE
LaTeX and PDF out of sync

### ISSUE THREAD

**Issue by maresb** [aseyboldt/covadapt-paper#1]
Seems to me like the PDF is best thought of as an artifact rather than being checked in. I've been meaning to look into GHA workflows, but haven't gotten around to it.

**Comment by maresb** [comment]
I'm writing because I really liked "Motivation: Example with an independent gaussian posterior" but didn't find it in the compiled version.

I wanted to correct this:

![image](https://github.com/user-attachments/assets/8887d49c-04e7-475c-bd23-c61eb8ec30a1)

I was sure that the formula for $\sigma^2$ had to be wrong since it looks so weird with a square on the LHS and square root on the RHS, but shockingly-to-me it's correct.

**Comment by aseyboldt** [comment]
I switched to typst, so the source is in `main.typ`. I guess I should delete a lot of unused files...

**Comment by aseyboldt** [comment]
And maybe it is more obvious why the formula would look like this if you think about it as $\sigma^2 = \text{geomean}(Var[x_i], Var[\alpha_i]^{-1}) = \exp(\log Var[x_i] / 2 - \log Var[\alpha_i] / 2)$.

**Comment by aseyboldt** [comment]
Should be in sync now with the github action :-)
